package consts

const (
	VALUES_SEPARATOR = "|"
	TASK_MESSAGE_SEPARATOR = "#"
	TIMEFRAME_SEPARATOR = "*"

	TIMEFRAME_MINUTES = "MINUTES" + VALUES_SEPARATOR
	TIMEFRAME_HOURS = "HOURS" + VALUES_SEPARATOR
	TIMEFRAME_MONTHES = "MONTHES" + VALUES_SEPARATOR
	TIMEFRAME_DOW = "DOW" + VALUES_SEPARATOR
	TIMEFRAME_DOM = "DOM" + VALUES_SEPARATOR

	FREQ_EVERY = "/"
	FREQ_INTERVAL = "-"
	FREQ_MANY = ","

	DELETE = "del"
)


var ShortWeekdays = [7]string{
	"Mon",
	"Tue",
	"Wed",
	"Thu",
	"Fri",
	"Sat",
	"Sun",
}